=== Liard-Thomas/jmeter/bin/templates/templates.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://jmeter.apache.org/"
	xmlns="https://jmeter.apache.org/" elementFormDefault="qualified">

	<!-- parameters element -->
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="key" type="xs:string" use="required"/>
						<xs:attribute name="defaultValue" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- templates element, body of the xml document -->
	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="template" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="fileName" type="xs:string" />
							<xs:element name="description" type="xs:string" />
							<xs:element ref="parameters" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="isTestPlan" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Liard-Thomas/jmeter/test/resources/org/apache/jmeter/gui/action/template/validTemplates.xml
<jm:templates
    xmlns:jm="http://jmeter.apache.org/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://jmeter.apache.org/ templates.xsd">
	<template isTestPlan="false">
		<name>testTemplateNotTestPlan</name>
		<fileName>/bin/templates/testTemplateNotTestPlan.jmx</fileName>
		<description>testTemplateNotTestPlan desc</description>
	</template>
	<template isTestPlan="true">
		<name>testTemplate</name>
		<fileName>/bin/templates/testTemplate.jmx</fileName>
		<description>testTemplate desc</description>
	</template>
	<template isTestPlan="true">
		<name>testTemplateWithParameters</name>
		<fileName>/bin/templates/testTemplate.jmx.fmkr</fileName>
		<description>Template with parameters</description>
		<parameters>
			<parameter key="testKey1" defaultValue="n 1" />
			<parameter key="testKey2" defaultValue="n 2" />
			<parameter key="testKey3" defaultValue="n 3" />
		</parameters>
	</template>
</jm:templates>
